[build]
  command = "npm run build:web"
  publish = "dist/client"

[dev]
  command = "npm run dev"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
